### PR TITLE
Translation File Update and gamemodes with resource folders creation

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Comment by tpan496** [comment]
why are a lot of files deleted? like the ones in `entities` folder

**Comment by Blueberryy** [comment]
Thet are not deleted they just moved

**Comment by Blueberryy** [comment]
> They are not deleted they just moved

Ah wait how did i did that? They actually removed

**Comment by Blueberryy** [comment]
Hmm, weird. When i tried to download entities from main repository and push it said that there's no differences

**Comment by Blueberryy** [comment]
Ah if you scroll down you will see that entity file that was renamed i guess it's 'deleted' one

**Comment by Blueberryy** [comment]
You can check this entity exist on my fork https://github.com/Blueberryy/Horde/tree/main/gamemodes/horde/entities/entities/horde_edible_gib

**Pull request closed without merging**
